### ISSUE TITLE
Onderzoek naar PvE - Best, good & bad practices

### ISSUE THREAD

**Issue by dipsaus9** [dipsaus9/parlor-docs#8]
Dit onderdeel zal tijdens alle onderzoeken door kunnen en zal voornamelijk een deskresearch worden. Kijk naar voorbeelden van concurrenten en andere stakeholders. Wat ging er goed en wat ging er fout. Overleg dit met CMD werkgroep en Matise. Leg wat voorbeelden neer en kijk of deze groep hetzelfde probleem ziet.

**Comment by dipsaus9** [comment]
Kijk naar voorbeelden zoals:
https://www.behance.net/gallery/71852913/Golden-Suisse

Wat vinden anderen hiervan?

**Comment by dipsaus9** [comment]
Contact opnemen met bedrijven die dit ook ervaren?

**Comment by timborst** [comment]
bbbcycling.com
kalkhoff-bikes.com 

😉
